# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_eta <- function(X, theta, BQ2, gamma, xi, t) {
    .Call(`_RSTGAM_compute_eta`, X, theta, BQ2, gamma, xi, t)
}

compute_gradient_gamma <- function(BQ2, temp3, P, gamma, lambda1) {
    .Call(`_RSTGAM_compute_gradient_gamma`, BQ2, temp3, P, gamma, lambda1)
}

compute_gradient_theta <- function(X, temp3) {
    .Call(`_RSTGAM_compute_gradient_theta`, X, temp3)
}

